name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # release-ready:
  #   name: Release ready
  #   needs: [release-win, release-linux]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-win:
    name: Release Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: build
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - run: ls -la target/x86_64-pc-windows-gnu/release
      - name: Release
        uses: xresloader/upload-to-github-release@v1.1.0
        with:
          file: 'target/x86_64-pc-windows-gnu/release/env2js.exe'
          tags: true
          overwrite: true
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-linux:
    name: Release Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt install upx-ucl binutils
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build
          args: --release
      - name: Copy build
        run: cp target/release/env2js target/release/env2js.min
      - name: Strip symbols
        run: strip target/release/env2js.min
      - name: Pack executable
        run: upx-ucl --best target/release/env2js.min -o target/release/env2js.nano
      - name: Release
        uses: xresloader/upload-to-github-release@v1.1.0
        with:
          file: 'target/release/env2js;target/release/env2js.min;target/release/env2js.nano'
          tags: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
