name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt install upx-ucl binutils
      - name: Build
        run: cargo build --release
      - name: Copy build
        run: cp target/release/env2js target/release/env2js.min
      - name: Strip symbols
        run: strip target/release/env2js.min
      - name: Pack executable
        run: upx-ucl target/release/env2js.min
      - uses: actions/upload-artifact@v1
        with:
          name: env2js
          path: target/release/env2js
      - uses: actions/upload-artifact@v1
        with:
          name: env2js.min
          path: target/release/env2js.min
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/env2js
            target/release/env2js.min
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
